apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-aws-service
spec:
  selector:
    matchLabels:
      run: kafka-aws-service
  template:
    metadata:
      labels:
        run: kafka-aws-service
    spec:
      containers:
      - name: kafka-aws-service
        image: yugansethu/aws-kafkastream-dynamodb:super
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-aws-service
  labels:
    run: kafka-aws-service
spec:
  ports:
  - port: 8081
    protocol: TCP
  type: LoadBalanacer
  selector:
    run: kafka-aws-service
