apiVersion: v1
kind: Service
metadata:
  name: secure-callme-bundle
  labels:
    run: secure-callme-bundle
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    run: secure-callme-bundle