package com.pim.Merchandise.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductInfo {
	private String modelNo;
	private String  uuId;
	private String skuId;
	private String categories;
	private String enabled;
	private String category;
	private String groups;
	private String colors;
	private String closurtype;
	private String specificDetails;
	private String pattern;
	private String customsCountry;
	private String customsDescription;
	private String customsMaterial;
	private String description;
	private String erpName;
	private String genderType;
	private String onlineDate;
	private String imageUrl;
	private String image;
	private String image3;
	private String longDescription;
	private String madeIn;
	private String material;
	private String metadescription;
	private String keywords;
	private String metatitle;
	private String price;
	private String StyleName;
	private String styleFamilyCode;
	private String productSpecificColor;
	private String productSpecificdescription;
	private String productSpecificInnerDesc;
	private String productSpecificStrapDesc;
	private String copywriters;
	private String customCounty;
	private String customDesc;
	private String customMaterial;
	private String engDesc;
	private String chinnaDesc;
	private String spainDesc;
	private String designer;
	private String designerId;
	private String engERP;
	private String chinnaERP;
	private String spainERP;
	private String designerColor;
	private String exclusive;
	private String materialDeatail;
	private String spainLongDesc;
	private String madein;
	private String spainMetaDesc;
	private String chinaMetaDesc;
	private String spainKeywords;
	private String chinaKeywords;
	private String metaTitle;
	private String spainmetaTitle;
	private String chinnametaTitle;
	private String productName;
	private String spainName;
	private String chinaName;
	private String nonTextileAnimalOrgin;
	private String onlilneCode;
	private String euroPrice;
	private String runWay;
	private String runwayImg;
	private String spainStyleName;
	private String chinaStyleName;
	private String tmallCategories;
	private String tmallDesc;
	private String spainTmallDesc;
	private String chinaTmallDesc;
	private String tmallTitle;
	private String spaintmallTitle;
	private String chinatmallTitle;
	private String vendorItemNo;
	private String size;
	private String features;
	private String curvedScreen;
	private String brand;
	private String builtinSpeakers;
	private String bluetoothEnabled;
	private String inch;
	
}
